import { Colors, Fonts } from "@/constants/theme";
import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get("window");
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bg,
  },
  headerWrapper: {
    flex: 1,
    backgroundColor: Colors["secondary-100"],
  },
  header: {
    backgroundColor: "#CBF2F6",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  headerLeft: {
    flex: 1,
  },
  starContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FF6B35",
    alignItems: "center",
    justifyContent: "center",
  },
  starIcon: {
    fontSize: 16,
    color: "white",
  },
  headerRightIcon: {
    height: 25,
    width: 25,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerButton: {
    marginLeft: 15,
  },
  headerIcon: {
    width: 30,
    height: 30,
  },
  userInfo: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 15,
    backgroundColor: "#CBF2F6",
  },
  profilePhoto: {
    width: 34,
    height: 34,
    borderRadius: 16,
    backgroundColor: "#E0E0E0",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  profileEmoji: {
    fontSize: 18,
  },
  userDetails: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  userName: {
    fontSize: 18,
    fontWeight: "600",
    color: Colors.text,
    marginRight: 5,
  },
  dropdownIcon: {
    marginTop: 5,
    fontWeight: "600",
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  piperIntroContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
    width: width,
    paddingHorizontal: 30,
  },
  alexPersonalImg: {
    width: 126,
    height: 180,
    resizeMode: "contain",
  },
  piperDetailsCard: {
    backgroundColor: "#FFF3E9",
    borderRadius: 15,
    padding: 12,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    textAlign: "center",
  },
  piperCard: {
    borderRadius: 20,
    marginBottom: 25,
    overflow: "hidden",
  },
  piperContent: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
  },
  piperTextContainer: {
    flex: 1,
  },
  piperGreeting: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#007AFF",
    marginBottom: 5,
  },
  piperDescription: {
    fontSize: 14,
    color: "#666",
    lineHeight: 18,
    marginBottom: 15,
  },
  tourButton: {
    backgroundColor: "#007AFF",
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 10,
    alignSelf: "flex-start",
  },
  tourButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
  },
  piperCharacterContainer: {
    width: 120,
    height: 120,
    backgroundColor: "rgba(255,255,255,0.3)",
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  piperCharacterEmoji: {
    fontSize: 60,
  },
  sectionContainer: {
    paddingHorizontal: 22,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 15,
    textAlign: "center",
  },
  progressCard: {
    backgroundColor: "#FFF3E9",
    borderRadius: 12,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    borderBlockColor: Colors.black,
    borderWidth: 1,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  progressTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
  },
  progressStatus: {
    flexDirection: "row",
    alignItems: "center",
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#FF9500",
    marginRight: 5,
  },
  statusText: {
    fontSize: 14,
    color: "#666",
    marginRight: 5,
  },
  chevronRight: {
    fontSize: 16,
    color: "#C7C7CC",
    fontWeight: "bold",
  },
  chartContainer: {
    flexDirection: "row",
    // alignItems: "end",

    justifyContent: "space-between",
    height: 100,
  },
  chartItem: {
    alignItems: "center",
    flex: 1,
  },
  barContainer: {
    height: 80,
    justifyContent: "flex-end",
    alignItems: "center",
    marginBottom: 10,
  },
  progressBar: {
    width: 8,
    borderRadius: 4,
    minHeight: 8,
  },
  dayLabel: {
    fontSize: 14,
    color: "#8E8E93",
    fontWeight: "500",
  },
  cardDetailsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  cardView: {
    backgroundColor: "#F2F2F7",
    justifyContent: "space-between",
  },
  careTeamContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginHorizontal: 10,
    columnGap: 30,
    rowGap: 20,
  },
  careTeamMember: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#D8DFF7",
    marginBottom: 15,
    alignItems: "center",
  },
  memberText: {
    color: "#3B3D3B",
    fontFamily: Fonts.Medium,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 16,
    textAlign: "center",
  },

  careTeamMemberImg: {
    height: 70,
    width: 70,
    resizeMode: "cover",
    marginBottom: 5,
    paddingHorizontal: 24,
  },
  summarySection: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    marginBottom: 15,
    columnGap: 1,
  },
  summaryDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
    borderRadius: 20,
    backgroundColor: "#F2F2F7",
    width: width / 2.25,
  },
  summaryText: {
    fontFamily: Fonts.SemiBold,
    color: Colors.primary,
    width: "70%",
    fontSize: 14,
  },
  summaryImg: {
    height: 45,
    width: 45,
    resizeMode: "contain",
  },
});
export default styles;
